# Generated by Django 4.0.1 on 2022-03-20 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(db_column='d_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='d_name', max_length=45, null=True)),
                ('token', models.CharField(blank=True, max_length=45, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, db_column='d_registration_date')),
                ('last_update', models.DateTimeField(blank=True, db_column='d_last_update', null=True)),
                ('is_online', models.BooleanField(db_column='d_is_online', default=False)),
                ('mac_address', models.CharField(blank=True, db_column='d_mac_address', max_length=45, null=True)),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(db_column='e_id', primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, db_column='e_score', decimal_places=2, max_digits=2, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='e_start_date', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='e_end_date', null=True)),
                ('device', models.ForeignKey(blank=True, db_column='e_device_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.device')),
            ],
            options={
                'db_table': 'experiment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(db_column='pl_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='pl_name', max_length=45)),
                ('supplier', models.CharField(blank=True, db_column='pl_supplier', max_length=45, null=True)),
            ],
            options={
                'db_table': 'plant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(db_column='r_id', max_length=45, primary_key=True, serialize=False)),
                ('data', models.CharField(blank=True, db_column='r_data', max_length=45, null=True)),
            ],
            options={
                'db_table': 'recipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.AutoField(db_column='po_id', primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, db_column='po_position', null=True)),
                ('experiment', models.ForeignKey(db_column='er_experiment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.experiment')),
                ('plant', models.ForeignKey(blank=True, db_column='po_plant_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.plant')),
            ],
            options={
                'db_table': 'pod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExperimentReading',
            fields=[
                ('id', models.AutoField(db_column='er_id', primary_key=True, serialize=False)),
                ('water_level', models.IntegerField(blank=True, db_column='er_water_level', null=True)),
                ('reading_date', models.DateTimeField(auto_now_add=True, db_column='er_reading_date')),
                ('water_tds', models.IntegerField(blank=True, db_column='er_water_tds', null=True)),
                ('water_ph', models.IntegerField(blank=True, db_column='er_water_ph', null=True)),
                ('electrical_conductance', models.IntegerField(blank=True, db_column='er_electrical_conductance', null=True)),
                ('reservoir_tds', models.IntegerField(blank=True, db_column='er_reservoir_tds', null=True)),
                ('reservoir_ph', models.IntegerField(blank=True, db_column='er_reservoir_ph', null=True)),
                ('water_temp', models.DecimalField(blank=True, db_column='er_water_temp', decimal_places=2, max_digits=2, null=True)),
                ('fill_res_flag', models.BooleanField(db_column='er_fill_res_flag', default=False)),
                ('air_temp', models.DecimalField(blank=True, db_column='er_air_temp', decimal_places=2, max_digits=2, null=True)),
                ('air_hum', models.DecimalField(blank=True, db_column='er_air_hum', decimal_places=2, max_digits=2, null=True)),
                ('recipe_stage', models.IntegerField(blank=True, db_column='er_recipe_stage', null=True)),
                ('room_temp', models.DecimalField(blank=True, db_column='er_room_temp', decimal_places=2, max_digits=2, null=True)),
                ('room_hum', models.DecimalField(blank=True, db_column='er_room_hum', decimal_places=2, max_digits=2, null=True)),
                ('refill_reservoir_flag', models.BooleanField(db_column='er_refill_reservoir_flag', default=False)),
                ('photo_link', models.CharField(blank=True, db_column='er_photo_link', max_length=100, null=True)),
                ('nutrient_score', models.DecimalField(blank=True, db_column='er_nutrient_score', decimal_places=2, max_digits=2, null=True)),
                ('experiment', models.ForeignKey(blank=True, db_column='er_experiment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.experiment')),
            ],
            options={
                'db_table': 'experiment_reading',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod1',
            field=models.ForeignKey(blank=True, db_column='e_pod1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod10',
            field=models.ForeignKey(blank=True, db_column='e_pod10', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod2',
            field=models.ForeignKey(blank=True, db_column='e_pod2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod3',
            field=models.ForeignKey(blank=True, db_column='e_pod3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod4',
            field=models.ForeignKey(blank=True, db_column='e_pod4', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod5',
            field=models.ForeignKey(blank=True, db_column='e_pod5', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod6',
            field=models.ForeignKey(blank=True, db_column='e_pod6', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod7',
            field=models.ForeignKey(blank=True, db_column='e_pod7', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod8',
            field=models.ForeignKey(blank=True, db_column='e_pod8', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='pod9',
            field=models.ForeignKey(blank=True, db_column='e_pod9', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.pod'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='recipe',
            field=models.ForeignKey(blank=True, db_column='e_recipe_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.recipe'),
        ),
        migrations.AddField(
            model_name='device',
            name='experiment',
            field=models.ForeignKey(blank=True, db_column='d_experiment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.experiment'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, db_column='d_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
