# Generated by Django 4.0.1 on 2022-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_device_device_alter_experiment_experiment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(db_column='d_is_online', default=False),
        ),
    ]
