# Generated by Django 4.0.1 on 2022-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_experiment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentreading',
            name='air_hum',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='air_temp',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='room_hum',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='room_temp',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='water_tds',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='water_temp',
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='humidity',
            field=models.DecimalField(blank=True, db_column='er_humidity', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='temperature',
            field=models.DecimalField(blank=True, db_column='er_temperature', decimal_places=2, max_digits=2, null=True),
        ),
    ]
