# Generated by Django 4.0.1 on 2022-04-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_experimentreading_air_hum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, db_column='d_model', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod10_score',
            field=models.DecimalField(blank=True, db_column='er_pod10_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod1_score',
            field=models.DecimalField(blank=True, db_column='er_pod1_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod2_score',
            field=models.DecimalField(blank=True, db_column='er_pod2_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod3_score',
            field=models.DecimalField(blank=True, db_column='er_pod3_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod4_score',
            field=models.DecimalField(blank=True, db_column='er_pod4_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod5_score',
            field=models.DecimalField(blank=True, db_column='er_pod5_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod6_score',
            field=models.DecimalField(blank=True, db_column='er_pod6_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod7_score',
            field=models.DecimalField(blank=True, db_column='er_pod7_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod8_score',
            field=models.DecimalField(blank=True, db_column='er_pod8_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='pod9_score',
            field=models.DecimalField(blank=True, db_column='er_pod9_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='score',
            field=models.DecimalField(blank=True, db_column='pl_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='end_date',
            field=models.DateTimeField(blank=True, db_column='po_end_date', null=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='score',
            field=models.DecimalField(blank=True, db_column='po_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='stage',
            field=models.IntegerField(blank=True, db_column='po_state', null=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='start_date',
            field=models.DateTimeField(blank=True, db_column='po_start_date', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='score',
            field=models.DecimalField(blank=True, db_column='po_score', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='experiment',
            field=models.ForeignKey(db_column='po_experiment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.experiment'),
        ),
    ]
