# Generated by Django 4.0.1 on 2022-04-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_device_model_experimentreading_pod10_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='stage',
            field=models.IntegerField(db_column='po_state', default=0),
        ),
    ]
