# Generated by Django 4.0.4 on 2022-04-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_pod_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(db_column='r_id', primary_key=True, serialize=False)),
                ('water_level', models.IntegerField(blank=True, db_column='r_water_level', null=True)),
                ('reading_date', models.DateTimeField(auto_now_add=True, db_column='r_reading_date')),
                ('electrical_conductance', models.IntegerField(blank=True, db_column='r_electrical_conductance', null=True)),
                ('reservoir_tds', models.IntegerField(blank=True, db_column='r_reservoir_tds', null=True)),
                ('reservoir_ph', models.IntegerField(blank=True, db_column='r_reservoir_ph', null=True)),
                ('recipe_stage', models.IntegerField(blank=True, db_column='r_recipe_stage', null=True)),
                ('temperature', models.DecimalField(blank=True, db_column='r_temperature', decimal_places=2, max_digits=2, null=True)),
                ('humidity', models.DecimalField(blank=True, db_column='r_humidity', decimal_places=2, max_digits=2, null=True)),
                ('photo_link', models.CharField(blank=True, db_column='r_photo_link', max_length=100, null=True)),
                ('pod1_score', models.DecimalField(blank=True, db_column='r_pod1_score', decimal_places=2, max_digits=2, null=True)),
                ('pod2_score', models.DecimalField(blank=True, db_column='r_pod2_score', decimal_places=2, max_digits=2, null=True)),
                ('pod3_score', models.DecimalField(blank=True, db_column='r_pod3_score', decimal_places=2, max_digits=2, null=True)),
                ('pod4_score', models.DecimalField(blank=True, db_column='r_pod4_score', decimal_places=2, max_digits=2, null=True)),
                ('pod5_score', models.DecimalField(blank=True, db_column='r_pod5_score', decimal_places=2, max_digits=2, null=True)),
                ('pod6_score', models.DecimalField(blank=True, db_column='r_pod6_score', decimal_places=2, max_digits=2, null=True)),
                ('pod7_score', models.DecimalField(blank=True, db_column='r_pod7_score', decimal_places=2, max_digits=2, null=True)),
                ('pod8_score', models.DecimalField(blank=True, db_column='r_pod8_score', decimal_places=2, max_digits=2, null=True)),
                ('pod9_score', models.DecimalField(blank=True, db_column='r_pod9_score', decimal_places=2, max_digits=2, null=True)),
                ('pod10_score', models.DecimalField(blank=True, db_column='r_pod10_score', decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'reading',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.CharField(db_column='s_id', max_length=45, primary_key=True, serialize=False)),
                ('author', models.CharField(db_column='s_author', max_length=45)),
                ('days', models.IntegerField(db_column='s_days')),
                ('watering_cycles', models.IntegerField(db_column='s_watering_cycles')),
                ('nutrient_cycles', models.IntegerField(db_column='s_nutrient_cycles')),
                ('nutrient_type', models.CharField(blank=True, db_column='s_nutrient_type', max_length=45, null=True)),
                ('blue_intensity', models.IntegerField(db_column='s_blue_intensity')),
                ('red_intensity', models.IntegerField(db_column='s_red_intensity')),
                ('white1_intensity', models.IntegerField(db_column='s_white1_intensity')),
                ('white2_intensity', models.IntegerField(db_column='s_white2_intensity')),
                ('lights_on_hours', models.IntegerField(db_column='s_lights_on_hours')),
                ('score', models.DecimalField(blank=True, db_column='s_score', decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'stage',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='pod',
            old_name='stage',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='recipe',
        ),
        migrations.AddField(
            model_name='device',
            name='fill_res_flag',
            field=models.BooleanField(db_column='d_fill_res_flag', default=False),
        ),
        migrations.AddField(
            model_name='experiment',
            name='day',
            field=models.IntegerField(db_column='e_day', default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='stage_day',
            field=models.IntegerField(db_column='e_stage_day', default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='stages',
            field=models.CharField(blank=True, db_column='e_stages', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ExperimentReading',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='reading',
            name='experiment',
            field=models.ForeignKey(blank=True, db_column='r_experiment_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.experiment'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='recipe_stage',
            field=models.ForeignKey(blank=True, db_column='e_recipe_stage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.stage'),
        ),
    ]
