# Generated by Django 4.0.4 on 2022-05-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_experimentreading_podreading_device_experiment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutrientRecipe',
            fields=[
                ('id', models.CharField(db_column='nr_id', max_length=45, primary_key=True, serialize=False)),
                ('json_data', models.JSONField(db_column='nr_data')),
            ],
            options={
                'db_table': 'nutrient_recipe',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='podreading',
            name='bud_count',
            field=models.IntegerField(blank=True, db_column='pr_bud_count', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='flower_count',
            field=models.IntegerField(blank=True, db_column='pr_flower_count', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='fruit_ripe_count',
            field=models.IntegerField(blank=True, db_column='pr_fruit_ripe_count', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='fruit_unripe_count',
            field=models.IntegerField(blank=True, db_column='pr_fruit_unripe_count', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='leaf_area_avg',
            field=models.DecimalField(blank=True, db_column='pr_leaf_area_avg', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='max_height',
            field=models.DecimalField(blank=True, db_column='pr_max_height', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='media_to_bgp',
            field=models.DecimalField(blank=True, db_column='pr_media_to_bgp', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='min_height',
            field=models.DecimalField(blank=True, db_column='pr_min_height', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='pod_phase',
            field=models.CharField(blank=True, db_column='pr_pod_phase', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='score',
            field=models.DecimalField(blank=True, db_column='pr_score', decimal_places=2, max_digits=5, null=True),
        ),
    ]
