# Generated by Django 4.0.4 on 2022-05-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_nutrientrecipe_podreading_bud_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.CharField(db_column='ph_id', max_length=45, primary_key=True, serialize=False)),
                ('author', models.CharField(db_column='ph_author', max_length=45)),
                ('days', models.IntegerField(db_column='ph_days')),
                ('watering_cycles', models.IntegerField(db_column='ph_watering_cycles')),
                ('nutrient_cycles', models.IntegerField(db_column='ph_nutrient_cycles')),
                ('nutrient_type', models.CharField(blank=True, db_column='ph_nutrient_type', max_length=45, null=True)),
                ('blue_intensity', models.IntegerField(db_column='ph_blue_intensity')),
                ('red_intensity', models.IntegerField(db_column='ph_red_intensity')),
                ('white1_intensity', models.IntegerField(db_column='ph_white1_intensity')),
                ('white2_intensity', models.IntegerField(db_column='ph_white2_intensity')),
                ('lights_on_hours', models.IntegerField(db_column='ph_lights_on_hours')),
            ],
            options={
                'db_table': 'phase',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='podreading',
            old_name='harvest_number',
            new_name='harvest_count',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod1',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod10',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod2',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod3',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod4',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod5',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod6',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod7',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod8',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='pod9',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='stage_day',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='recipe_stage',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='flower_number',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='flower_weight',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='plant_height',
        ),
        migrations.AddField(
            model_name='experiment',
            name='phase_day',
            field=models.IntegerField(db_column='e_phase_day', default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='phases',
            field=models.CharField(blank=True, db_column='e_phases', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='experiment_phase',
            field=models.IntegerField(blank=True, db_column='er_experiment_phase', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='domes',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.AddField(
            model_name='experiment',
            name='current_phase',
            field=models.ForeignKey(blank=True, db_column='e_current_phase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dashboard.phase'),
        ),
    ]
