# Generated by Django 4.0.4 on 2022-05-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_phase_rename_harvest_number_podreading_harvest_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='score',
            field=models.DecimalField(blank=True, db_column='ph_score', decimal_places=2, max_digits=2, null=True),
        ),
    ]
