# Generated by Django 4.0.4 on 2022-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_phase_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='state',
        ),
        migrations.AddField(
            model_name='pod',
            name='phase',
            field=models.IntegerField(db_column='po_phase', default=0),
        ),
    ]
