# Generated by Django 4.0.4 on 2022-05-16 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_remove_pod_state_pod_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='type',
            field=models.CharField(db_column='ph_type', default='Germination', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phase',
            name='author',
            field=models.ForeignKey(blank=True, db_column='ph_author', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
