# Generated by Django 4.0.4 on 2022-05-25 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_remove_experiment_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='plant',
            field=models.ForeignKey(db_column='po_plant_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.plant'),
            preserve_default=False,
        ),
    ]
