# Generated by Django 4.0.4 on 2022-05-27 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0028_remove_device_experiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='author',
        ),
        migrations.AddField(
            model_name='phase',
            name='user',
            field=models.ForeignKey(blank=True, db_column='ph_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(db_column='r_id', primary_key=True, serialize=False)),
                ('precidence', models.IntegerField(db_column='r_precidence')),
                ('experiment', models.ForeignKey(db_column='r_experiment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.experiment')),
                ('phase', models.ForeignKey(db_column='r_phase_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.phase')),
            ],
        ),
    ]
