# Generated by Django 4.0.4 on 2022-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_phase_author_phase_user_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='white1_intensity',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='white2_intensity',
        ),
        migrations.AddField(
            model_name='phase',
            name='white_intensity',
            field=models.IntegerField(db_column='ph_white_intensity', default=100),
            preserve_default=False,
        ),
    ]
