# Generated by Django 4.0.4 on 2022-05-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_phase_white1_intensity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='nutrient_type',
        ),
    ]
