# Generated by Django 4.0.4 on 2022-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_phase_nutrient_cycles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='watering_cycles',
        ),
        migrations.AddField(
            model_name='phase',
            name='watering_duration',
            field=models.IntegerField(db_column='ph_watering_duration', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='waterings_per_day',
            field=models.IntegerField(db_column='ph_waterings_per_day', default=1),
            preserve_default=False,
        ),
    ]
