# Generated by Django 4.0.4 on 2022-06-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_recipe_experiment_remove_recipe_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='num_pods',
        ),
        migrations.AddField(
            model_name='device',
            name='device_capacity',
            field=models.IntegerField(db_column='d_device_capacity', default=5),
        ),
    ]
