# Generated by Django 4.0.4 on 2022-06-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remove_device_num_pods_device_device_capacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
