# Generated by Django 4.0.4 on 2022-06-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(db_column='r_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='r_name', default='NO RECIPE NAME', max_length=45)),
                ('phase1', models.ForeignKey(blank=True, db_column='r_phase1_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase1', to='dashboard.phase')),
                ('phase10', models.ForeignKey(blank=True, db_column='r_phase10_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase10', to='dashboard.phase')),
                ('phase2', models.ForeignKey(blank=True, db_column='r_phase2_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase2', to='dashboard.phase')),
                ('phase3', models.ForeignKey(blank=True, db_column='r_phase3_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase3', to='dashboard.phase')),
                ('phase4', models.ForeignKey(blank=True, db_column='r_phase4_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase4', to='dashboard.phase')),
                ('phase5', models.ForeignKey(blank=True, db_column='r_phase5_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase5', to='dashboard.phase')),
                ('phase6', models.ForeignKey(blank=True, db_column='r_phase6_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase6', to='dashboard.phase')),
                ('phase7', models.ForeignKey(blank=True, db_column='r_phase7_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase7', to='dashboard.phase')),
                ('phase8', models.ForeignKey(blank=True, db_column='r_phase8_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase8', to='dashboard.phase')),
                ('phase9', models.ForeignKey(blank=True, db_column='r_phase9_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phase9', to='dashboard.phase')),
            ],
        ),
    ]
