# Generated by Django 4.0.4 on 2022-06-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_experiment_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_capacity',
        ),
        migrations.AddField(
            model_name='device',
            name='capacity',
            field=models.IntegerField(db_column='d_capacity', default=5),
        ),
        migrations.AlterField(
            model_name='pod',
            name='experiment',
            field=models.ForeignKey(db_column='po_experiment_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.experiment'),
        ),
    ]
