# Generated by Django 4.0.4 on 2022-06-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_podreading_pod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
