# Generated by Django 4.0.4 on 2022-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_experiment_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='days',
            field=models.IntegerField(db_column='r_days', default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_json',
            field=models.CharField(blank=True, db_column='r_recipe_json', max_length=4096, null=True),
        ),
    ]
