# Generated by Django 4.0.4 on 2022-07-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_recipe_days_alter_recipe_recipe_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentreading',
            name='reservoir_tds',
        ),
    ]
