# Generated by Django 4.0.4 on 2022-07-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_remove_experimentreading_reservoir_tds'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hour',
            field=models.IntegerField(db_column='d_hour', default=12),
        ),
        migrations.AddField(
            model_name='device',
            name='minute',
            field=models.IntegerField(db_column='d_minute', default=59),
        ),
    ]
