# Generated by Django 4.0.4 on 2022-07-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_device_hour_device_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='device',
            name='minute',
        ),
    ]
