# Generated by Django 4.0.4 on 2022-07-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_device_hour_remove_device_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podreading',
            name='internode_distance',
            field=models.DecimalField(blank=True, db_column='pr_internode_distance', decimal_places=2, max_digits=5, null=True),
        ),
    ]
