# Generated by Django 4.0.4 on 2022-07-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_podreading_internode_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podreading',
            name='harvest_count',
            field=models.IntegerField(db_column='pr_harvest_count', default=False),
        ),
    ]
