# Generated by Django 4.0.4 on 2022-07-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_alter_podreading_algae_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podreading',
            name='algae_coverage',
            field=models.IntegerField(db_column='pr_algae_coverage', default=False),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='blight_coverage',
            field=models.IntegerField(db_column='pr_blight_coverage', default=False),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='pest_coverage',
            field=models.IntegerField(db_column='pr_pest_coverage', default=False),
        ),
    ]
