# Generated by Django 4.0.4 on 2022-07-08 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_podreading_algae_coverage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podreading',
            name='seeds_germinated',
        ),
        migrations.AddField(
            model_name='plant',
            name='bgp_distance',
            field=models.IntegerField(blank=True, db_column='pl_bgp_distance', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='bud_count',
            field=models.IntegerField(blank=True, db_column='pl_bud_count', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_final_harvest',
            field=models.IntegerField(blank=True, db_column='pl_days_to_final_harvest', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_first_harvest',
            field=models.IntegerField(blank=True, db_column='pl_days_to_first_harvest', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_germinate_max',
            field=models.IntegerField(blank=True, db_column='pl_days_to_germinate_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_germinate_min',
            field=models.IntegerField(blank=True, db_column='pl_days_to_germinate_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_count',
            field=models.IntegerField(blank=True, db_column='pl_flower_count', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='flower_quality',
            field=models.IntegerField(db_column='pl_flower_quality', default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruit_ripe_count',
            field=models.IntegerField(blank=True, db_column='pl_fruit_ripe_count', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='fruit_unripe_count',
            field=models.IntegerField(blank=True, db_column='pl_fruit_unripe_count', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='germination_rate',
            field=models.IntegerField(blank=True, db_column='pl_germination_rate', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='harvest_count',
            field=models.IntegerField(db_column='pl_harvest_count', default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='harvest_quality',
            field=models.IntegerField(blank=True, db_column='pl_harvest_quality', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='harvest_weight',
            field=models.DecimalField(blank=True, db_column='pl_harvest_weight', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='internode',
            field=models.IntegerField(blank=True, db_column='pl_internode', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='leaf_count',
            field=models.IntegerField(blank=True, db_column='pl_leaf_count', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='max_final_height',
            field=models.IntegerField(blank=True, db_column='pl_max_final_height', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='mean_leaf_area',
            field=models.IntegerField(blank=True, db_column='pl_mean_leaf_area', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='min_final_height',
            field=models.IntegerField(blank=True, db_column='pl_min_final_height', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='node_count',
            field=models.IntegerField(blank=True, db_column='pl_node_count', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='germination_rate',
            field=models.IntegerField(blank=True, db_column='pr_germination_rate', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='experimentreading',
            name='humidity',
            field=models.IntegerField(blank=True, db_column='er_humidity', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='algae_coverage',
            field=models.IntegerField(db_column='pr_algae_coverage', default=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='blight_coverage',
            field=models.IntegerField(db_column='pr_blight_coverage', default=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='harvest_quality',
            field=models.IntegerField(blank=True, db_column='pr_harvest_quality', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='pest_coverage',
            field=models.IntegerField(db_column='pr_pest_coverage', default=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
