# Generated by Django 4.0.4 on 2022-07-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_remove_podreading_seeds_germinated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='days_to_final_harvest',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='days_to_first_harvest',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='days_to_germinate_max',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='days_to_germinate_min',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='max_final_height',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='mean_leaf_area',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='min_final_height',
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_germinate',
            field=models.IntegerField(blank=True, db_column='pl_days_to_germinate', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_harvest',
            field=models.IntegerField(blank=True, db_column='pl_days_to_harvest', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_height',
            field=models.IntegerField(blank=True, db_column='pl_final_height', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='leaf_area',
            field=models.IntegerField(blank=True, db_column='pl_leaf_area', null=True),
        ),
    ]
