# Generated by Django 4.0.4 on 2022-07-08 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_remove_plant_days_to_final_harvest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='flower_quality',
            field=models.IntegerField(blank=True, db_column='pl_flower_quality', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='flower_quality',
            field=models.IntegerField(blank=True, db_column='pr_flower_quality', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
