# Generated by Django 4.0.4 on 2022-07-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_alter_plant_flower_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='harvest_count',
            field=models.IntegerField(blank=True, db_column='pl_harvest_count', null=True),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='harvest_count',
            field=models.IntegerField(blank=True, db_column='pr_harvest_count', null=True),
        ),
    ]
