# Generated by Django 4.0.4 on 2022-07-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_plant_harvest_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='bgp_distance',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='bud_count',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='days_to_germinate',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='days_to_harvest',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='final_height',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='internode',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaf_area',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='leaf_count',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='node_count',
        ),
        migrations.AddField(
            model_name='plant',
            name='bgp_distance_max',
            field=models.IntegerField(blank=True, db_column='pl_bgp_distance_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='bgp_distance_min',
            field=models.IntegerField(blank=True, db_column='pl_bgp_distance_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='bud_count_max',
            field=models.IntegerField(blank=True, db_column='pl_bud_count_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='bud_count_min',
            field=models.IntegerField(blank=True, db_column='pl_bud_count_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_germinate_max',
            field=models.IntegerField(blank=True, db_column='pl_days_to_germinate_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_germinate_min',
            field=models.IntegerField(blank=True, db_column='pl_days_to_germinate_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_harvest_max',
            field=models.IntegerField(blank=True, db_column='pl_days_to_harvest_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_harvest_min',
            field=models.IntegerField(blank=True, db_column='pl_days_to_harvest_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_height_max',
            field=models.IntegerField(blank=True, db_column='pl_final_height_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_height_min',
            field=models.IntegerField(blank=True, db_column='pl_final_height_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_leaf_area_max',
            field=models.IntegerField(blank=True, db_column='pl_final_leaf_area_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_leaf_area_min',
            field=models.IntegerField(blank=True, db_column='pl_final_leaf_area_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_leaf_count_max',
            field=models.IntegerField(blank=True, db_column='pl_final_leaf_count_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='final_leaf_count_min',
            field=models.IntegerField(blank=True, db_column='pl_final_leaf_count_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='internode_distance_max',
            field=models.IntegerField(blank=True, db_column='pl_internode_distance_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='internode_distance_min',
            field=models.IntegerField(blank=True, db_column='pl_internode_distance_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='node_count_max',
            field=models.IntegerField(blank=True, db_column='pl_node_count_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='node_count_min',
            field=models.IntegerField(blank=True, db_column='pl_node_count_min', null=True),
        ),
    ]
