# Generated by Django 4.0.4 on 2022-08-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_json',
            field=models.JSONField(db_column='r_recipe_json'),
        ),
    ]
