# Generated by Django 4.0.4 on 2022-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_recipe_recipe_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_json',
            field=models.JSONField(blank=True, db_column='r_recipe_json', null=True),
        ),
    ]
