# Generated by Django 4.0.4 on 2022-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_alter_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(db_column='d_id', max_length=45, primary_key=True, serialize=False),
        ),
    ]
