# Generated by Django 4.0.4 on 2022-08-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_remove_device_token_alter_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_online',
        ),
        migrations.AddField(
            model_name='device',
            name='online',
            field=models.BooleanField(db_column='d_online', default=False),
        ),
    ]
