# Generated by Django 4.0.4 on 2022-08-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_recipe_recipe_json'),
        ('dashboard', '0065_remove_device_online_device_is_online'),
    ]

    operations = [
    ]
