# Generated by Django 4.0.4 on 2022-08-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_merge_20220811_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pod',
            name='plant',
            field=models.ForeignKey(db_column='po_plant_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.plant'),
        ),
    ]
