# Generated by Django 4.0.4 on 2022-08-25 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_remove_experiment_current_phase_experiment_phase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='days_to_germinate_max',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='days_to_germinate_min',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='supplier',
        ),
        migrations.AddField(
            model_name='plant',
            name='culinary',
            field=models.CharField(blank=True, db_column='pl_culinary', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_sprout_max',
            field=models.IntegerField(blank=True, db_column='pl_days_to_sprout_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='days_to_sprout_min',
            field=models.IntegerField(blank=True, db_column='pl_days_to_sprout_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='fun_facts',
            field=models.CharField(blank=True, db_column='pl_fun_facts', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='growing_tips',
            field=models.CharField(blank=True, db_column='pl_growing_tips', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='harvesting_tips',
            field=models.CharField(blank=True, db_column='pl_harvesting_tips', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_days_to_harvest',
            field=models.IntegerField(blank=True, db_column='pl_ideal_days_to_harvest', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_ec_max',
            field=models.DecimalField(blank=True, db_column='pl_ideal_ec_max', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_ec_min',
            field=models.DecimalField(blank=True, db_column='pl_ideal_ec_min', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_humidity_max',
            field=models.IntegerField(blank=True, db_column='pl_ideal_humidity_max', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_humidity_min',
            field=models.IntegerField(blank=True, db_column='pl_ideal_humidity_min', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_ph_max',
            field=models.DecimalField(blank=True, db_column='pl_ideal_ph_max', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_ph_min',
            field=models.DecimalField(blank=True, db_column='pl_ideal_ph_min', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temp_max',
            field=models.IntegerField(blank=True, db_column='pl_ideal_temp_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temp_min',
            field=models.IntegerField(blank=True, db_column='pl_ideal_temp_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_water_temp_max',
            field=models.IntegerField(blank=True, db_column='pl_ideal_water_temp_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_water_temp_min',
            field=models.IntegerField(blank=True, db_column='pl_ideal_water_temp_min', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='medical_uses',
            field=models.CharField(blank=True, db_column='pl_medical_uses', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='nutritional_benefits',
            field=models.CharField(blank=True, db_column='pl_nutritional_benefits', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='profile',
            field=models.CharField(blank=True, db_column='pl_profile', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, db_column='pl_scientific_name', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='storage',
            field=models.CharField(blank=True, db_column='pl_storage', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.CharField(db_column='pl_id', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, db_column='pl_name', max_length=45, null=True),
        ),
    ]
