# Generated by Django 4.0.4 on 2022-08-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_remove_plant_days_to_germinate_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ideal_days_to_sprout_max',
            field=models.IntegerField(blank=True, db_column='pl_ideal_days_to_sprout_max', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_days_to_sprout_min',
            field=models.IntegerField(blank=True, db_column='pl_ideal_days_to_sprout_min', null=True),
        ),
    ]
