# Generated by Django 4.0.4 on 2022-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_plant_ideal_days_to_sprout_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podreading',
            name='dome',
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='failed_pump',
            field=models.BooleanField(db_column='er_failed_pump', null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='flushed_reservoir',
            field=models.BooleanField(db_column='er_flushed_reservoir', null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='lost_power',
            field=models.BooleanField(db_column='er_lost_power', null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='raised_light',
            field=models.BooleanField(db_column='er_raised_light', null=True),
        ),
        migrations.AddField(
            model_name='experimentreading',
            name='went_offline',
            field=models.BooleanField(db_column='er_went_offline', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='pest_removal',
            field=models.BooleanField(db_column='pr_pest_removal', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='pollinated',
            field=models.BooleanField(db_column='pr_pollinated', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='prune_dead_foliage',
            field=models.BooleanField(db_column='pr_prune_dead_foliage', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='prune_dead_heading',
            field=models.BooleanField(db_column='pr_prune_dead_heading', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='prune_living_foliage',
            field=models.BooleanField(db_column='pr_prune_living_foliage', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='prune_thinned',
            field=models.BooleanField(db_column='pr_prune_thinned', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='prune_topped',
            field=models.BooleanField(db_column='pr_prune_topped', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='removed_dome',
            field=models.BooleanField(db_column='pr_removed_dome', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='trellis_adjustment',
            field=models.BooleanField(db_column='pr_trellis_adjustment', null=True),
        ),
    ]
