# Generated by Django 4.0.4 on 2022-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_remove_podreading_dome_experimentreading_failed_pump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentreading',
            name='failed_pump',
            field=models.BooleanField(db_column='er_failed_pump', default=0),
        ),
        migrations.AlterField(
            model_name='experimentreading',
            name='flushed_reservoir',
            field=models.BooleanField(db_column='er_flushed_reservoir', default=0),
        ),
        migrations.AlterField(
            model_name='experimentreading',
            name='lost_power',
            field=models.BooleanField(db_column='er_lost_power', default=0),
        ),
        migrations.AlterField(
            model_name='experimentreading',
            name='raised_light',
            field=models.BooleanField(db_column='er_raised_light', default=0),
        ),
        migrations.AlterField(
            model_name='experimentreading',
            name='went_offline',
            field=models.BooleanField(db_column='er_went_offline', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='pest_removal',
            field=models.BooleanField(db_column='pr_pest_removal', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='pollinated',
            field=models.BooleanField(db_column='pr_pollinated', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='prune_dead_foliage',
            field=models.BooleanField(db_column='pr_prune_dead_foliage', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='prune_dead_heading',
            field=models.BooleanField(db_column='pr_prune_dead_heading', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='prune_living_foliage',
            field=models.BooleanField(db_column='pr_prune_living_foliage', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='prune_thinned',
            field=models.BooleanField(db_column='pr_prune_thinned', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='prune_topped',
            field=models.BooleanField(db_column='pr_prune_topped', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='removed_dome',
            field=models.BooleanField(db_column='pr_removed_dome', default=0),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='trellis_adjustment',
            field=models.BooleanField(db_column='pr_trellis_adjustment', default=0),
        ),
    ]
