# Generated by Django 4.0.4 on 2022-08-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_alter_experimentreading_failed_pump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentreading',
            name='temperature',
            field=models.DecimalField(blank=True, db_column='er_temperature', decimal_places=2, max_digits=5, null=True),
        ),
    ]
