# Generated by Django 4.0.4 on 2022-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_experimentreading_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentreading',
            name='reservoir_ph',
            field=models.DecimalField(blank=True, db_column='er_reservoir_ph', decimal_places=1, max_digits=2, null=True),
        ),
    ]
