# Generated by Django 4.0.4 on 2022-09-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_alter_experimentreading_experiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phase',
            name='user',
        ),
    ]
