# Generated by Django 4.0.4 on 2022-09-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_experiment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='status',
            field=models.IntegerField(db_column='po_status', default=0),
        ),
    ]
