# Generated by Django 4.0.4 on 2022-09-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_pod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='recipe',
            field=models.ForeignKey(db_column='ph_recipe_id', default=23, on_delete=django.db.models.deletion.CASCADE, to='dashboard.recipe'),
            preserve_default=False,
        ),
    ]
