# Generated by Django 4.0.4 on 2022-09-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_phase_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='recipe',
        ),
    ]
