# Generated by Django 4.0.4 on 2022-09-23 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_remove_phase_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podreading',
            name='algae_coverage',
            field=models.IntegerField(blank=True, db_column='pr_algae_coverage', default=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='blight_coverage',
            field=models.IntegerField(blank=True, db_column='pr_blight_coverage', default=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='podreading',
            name='pest_coverage',
            field=models.IntegerField(blank=True, db_column='pr_pest_coverage', default=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
