# Generated by Django 4.0.4 on 2022-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_alter_podreading_algae_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='genus',
            field=models.CharField(blank=True, db_column='pl_genus', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='nickname',
            field=models.CharField(blank=True, db_column='pl_nickname', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, db_column='pl_species', max_length=45, null=True),
        ),
    ]
