# Generated by Django 4.0.4 on 2022-10-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_remove_plant_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='culinary',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fun_facts',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='medical_uses',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='nutritional_benefits',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='storage',
        ),
    ]
