# Generated by Django 4.0.4 on 2022-10-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_remove_plant_culinary_remove_plant_fun_facts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
    ]
