# Generated by Django 4.0.4 on 2022-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_plant_genus_plant_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='nickname',
            field=models.CharField(blank=True, db_column='pl_nickname', max_length=45, null=True),
        ),
    ]
