# Generated by Django 4.0.4 on 2022-10-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_remove_plant_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='podreading',
            name='image_link',
            field=models.URLField(blank=True, db_column='pr_image_link', null=True),
        ),
    ]
