# Generated by Django 4.0.4 on 2022-10-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_podreading_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentreading',
            name='lost_power',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='photo_link',
        ),
        migrations.RemoveField(
            model_name='experimentreading',
            name='went_offline',
        ),
    ]
