# Generated by Django 4.0.4 on 2022-10-08 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_alter_phase_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='podreading',
            name='electrical_conductance',
            field=models.IntegerField(blank=True, db_column='pr_electrical_conductance', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='failed_pump',
            field=models.BooleanField(db_column='pr_failed_pump', default=0),
        ),
        migrations.AddField(
            model_name='podreading',
            name='flushed_reservoir',
            field=models.BooleanField(db_column='pr_flushed_reservoir', default=0),
        ),
        migrations.AddField(
            model_name='podreading',
            name='humidity',
            field=models.IntegerField(blank=True, db_column='pr_humidity', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='podreading',
            name='raised_light',
            field=models.BooleanField(db_column='pr_raised_light', default=0),
        ),
        migrations.AddField(
            model_name='podreading',
            name='reading_date',
            field=models.DateTimeField(blank=True, db_column='pr_reading_date', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='reservoir_ph',
            field=models.DecimalField(blank=True, db_column='pr_reservoir_ph', decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='temperature',
            field=models.IntegerField(blank=True, db_column='pr_temperature', null=True),
        ),
        migrations.AddField(
            model_name='podreading',
            name='water_level',
            field=models.IntegerField(blank=True, db_column='pr_water_level', null=True),
        ),
    ]
