# Generated by Django 4.0.4 on 2022-10-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0097_podreading_electrical_conductance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podreading',
            name='electrical_conductance',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='failed_pump',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='flushed_reservoir',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='raised_light',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='reservoir_ph',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='podreading',
            name='water_level',
        ),
    ]
