# Generated by Django 4.0.4 on 2022-10-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_remove_podreading_electrical_conductance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podreading',
            name='reading_date',
            field=models.DateTimeField(auto_now_add=True, db_column='pr_reading_date'),
        ),
    ]
