# Generated by Django 4.0.4 on 2022-10-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_alter_podreading_reading_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podreading',
            name='reading_date',
        ),
    ]
