# Generated by Django 4.0.4 on 2022-10-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_remove_podreading_reading_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='genus',
        ),
    ]
